# Spring Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/testdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.ejmc
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: docs.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: fal경se
  h2:
    console:
      enabled: true
      path: /h2-console
